import React from "react";
import { Document, Page, Text, View, StyleSheet, pdf, Font, Image } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica", backgroundColor: "#FFFFFF" },
  header: { marginBottom: 24, borderBottomWidth: 2, borderBottomColor: "#C9956A", paddingBottom: 16 },
  brandRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  brandName: { fontSize: 22, fontWeight: "bold", color: "#0F172A" },
  tagline: { fontSize: 9, color: "#666666", marginTop: 3 },
  dateRange: { fontSize: 10, color: "#888888", textAlign: "right" },
  reportTitle: { fontSize: 16, fontWeight: "bold", color: "#0F172A", marginTop: 8 },
  kpiRow: { flexDirection: "row", gap: 12, marginBottom: 20 },
  kpiCard: { flex: 1, backgroundColor: "#F8F9FA", borderRadius: 8, padding: 12 },
  kpiLabel: { fontSize: 8, color: "#666666", textTransform: "uppercase", letterSpacing: 1 },
  kpiValue: { fontSize: 18, fontWeight: "bold", color: "#0F172A", marginTop: 4 },
  kpiSub: { fontSize: 7, color: "#999999", marginTop: 2 },
  sectionTitle: { fontSize: 13, fontWeight: "bold", color: "#0F172A", marginBottom: 10, marginTop: 16 },
  table: { marginBottom: 16 },
  tableHeader: { flexDirection: "row", backgroundColor: "#F1F5F9", borderTopLeftRadius: 6, borderTopRightRadius: 6, paddingVertical: 6, paddingHorizontal: 8 },
  tableHeaderCell: { fontSize: 8, fontWeight: "bold", color: "#475569", textTransform: "uppercase", letterSpacing: 0.5 },
  tableRow: { flexDirection: "row", paddingVertical: 5, paddingHorizontal: 8, borderBottomWidth: 0.5, borderBottomColor: "#E2E8F0" },
  tableCell: { fontSize: 9, color: "#334155" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, flexDirection: "row", justifyContent: "space-between", borderTopWidth: 0.5, borderTopColor: "#E2E8F0", paddingTop: 8 },
  footerText: { fontSize: 7, color: "#999999" },
  accentBar: { height: 4, backgroundColor: "#C9956A", borderRadius: 2, marginBottom: 16 },
});

interface PdfReportProps {
  brandName: string;
  tagline?: string;
  primaryColor?: string;
  logoUrl?: string;
  reportTitle: string;
  dateRange: string;
  kpis?: Array<{ label: string; value: string; sub?: string }>;
  tables?: Array<{ title: string; headers: string[]; rows: string[][]; widths?: number[] }>;
}

function ReportDocument({ brandName, tagline, primaryColor, reportTitle, dateRange, kpis, tables }: PdfReportProps) {
  const accent = primaryColor || "#C9956A";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={[styles.accentBar, { backgroundColor: accent }]} />
        <View style={styles.header}>
          <View style={styles.brandRow}>
            <View>
              <Text style={styles.brandName}>{brandName}</Text>
              {tagline && <Text style={styles.tagline}>{tagline}</Text>}
            </View>
            <Text style={styles.dateRange}>{dateRange}</Text>
          </View>
          <Text style={styles.reportTitle}>{reportTitle}</Text>
        </View>

        {kpis && kpis.length > 0 && (
          <View style={styles.kpiRow}>
            {kpis.slice(0, 4).map((kpi, i) => (
              <View key={i} style={styles.kpiCard}>
                <Text style={styles.kpiLabel}>{kpi.label}</Text>
                <Text style={styles.kpiValue}>{kpi.value}</Text>
                {kpi.sub && <Text style={styles.kpiSub}>{kpi.sub}</Text>}
              </View>
            ))}
          </View>
        )}

        {tables?.map((table, ti) => (
          <View key={ti} style={styles.table} wrap={false}>
            <Text style={styles.sectionTitle}>{table.title}</Text>
            <View style={styles.tableHeader}>
              {table.headers.map((h, i) => (
                <Text key={i} style={[styles.tableHeaderCell, { width: table.widths?.[i] ? `${table.widths[i]}%` : `${100 / table.headers.length}%` }]}>{h}</Text>
              ))}
            </View>
            {table.rows.slice(0, 50).map((row, ri) => (
              <View key={ri} style={styles.tableRow}>
                {row.map((cell, ci) => (
                  <Text key={ci} style={[styles.tableCell, { width: table.widths?.[ci] ? `${table.widths[ci]}%` : `${100 / table.headers.length}%` }]}>{cell}</Text>
                ))}
              </View>
            ))}
          </View>
        ))}

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by {brandName}</Text>
          <Text style={styles.footerText}>{new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</Text>
        </View>
      </Page>
    </Document>
  );
}

export async function generatePdfReport(props: PdfReportProps): Promise<void> {
  const blob = await pdf(<ReportDocument {...props} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${props.reportTitle.toLowerCase().replace(/\s+/g, "-")}-${new Date().toISOString().split("T")[0]}.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}
