import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import locationsRouter from "./locations";
import usersRouter from "./users";
import servicesRouter from "./services";
import appointmentsRouter from "./appointments";
import availabilityRouter from "./availability";
import reviewsRouter from "./reviews";
import analyticsRouter from "./analytics";
import giftCardsRouter from "./gift-cards";
import notificationsRouter from "./notifications";
import aiRouter from "./ai";
import anthropicRouter from "./anthropic";
import devRouter from "./dev";
import paymentsRouter from "./payments";
import messagesRouter from "./messages";
import waitlistRouter from "./waitlist";
import tipsRouter from "./tips";
import exploreRouter from "./explore";
import scheduleRouter from "./schedule";
import analyticsExtendedRouter from "./analytics-extended";
import platformRouter from "./platform";
import googleCalendarRouter from "./google-calendar";
import intakeFormsRouter from "./intake-forms";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(locationsRouter);
router.use(usersRouter);
router.use(servicesRouter);
router.use(appointmentsRouter);
router.use(availabilityRouter);
router.use(reviewsRouter);
router.use(analyticsRouter);
router.use(giftCardsRouter);
router.use(notificationsRouter);
router.use(aiRouter);
router.use(anthropicRouter);
router.use(devRouter);
router.use(paymentsRouter);
router.use(messagesRouter);
router.use(waitlistRouter);
router.use(tipsRouter);
router.use(exploreRouter);
router.use(scheduleRouter);
router.use(analyticsExtendedRouter);
router.use(platformRouter);
router.use(googleCalendarRouter);
router.use(intakeFormsRouter);

export default router;
